name: whoopit
description: Made with love by hummingbird.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.7
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  permission_handler: ^8.2.5
  rounded_loading_button: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
