name: whoopit
description: Made with love by hummingbird.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.7
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.3.4
  firebase_app_check: ^0.0.2+3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.4
  firebase_performance: ^0.7.1+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_native_splash: ^1.3.1
  google_fonts: ^2.0.0
  hooks_riverpod: ^0.14.0+5
  permission_handler: ^8.2.5
  rounded_loading_button: ^2.0.9
  shake: ^1.0.1
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
