name: whoopit
description: Made with love by hummingbird.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.4.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.7
  audio_session: ^0.1.6+1
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.7
  cloud_functions: ^3.0.4
  cupertino_icons: ^1.0.3
  emoji_picker_flutter: ^1.1.1
  firebase_analytics: ^9.1.0
  firebase_app_check: ^0.0.2+3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.4
  firebase_performance: ^0.8.0+5
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_keyboard_visibility: ^5.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  flutterfire_ui: ^0.3.2
  giphy_get: ^3.0.0
  google_fonts: ^2.0.0
  hooks_riverpod: ^1.0.1
  image_picker: ^0.8.4+4
  just_audio: ^0.9.18
  path_provider: ^2.0.7
  permission_handler: ^8.2.5
  rounded_loading_button: ^2.0.9
  shake: ^2.0.0
  share_plus: ^3.0.4
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/images/whoopit.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
