// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7iVr6u-tmOE_c589tlTr1vca3tLwxXo',
    appId: '1:418778353503:web:5dbf28856e74207bf370ea',
    messagingSenderId: '418778353503',
    projectId: 'fir-flutter-codelab-32edb',
    authDomain: 'fir-flutter-codelab-32edb.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-32edb.appspot.com',
    measurementId: 'G-QTCF04VSSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IYgwb5rY3S8SpYWwUm_lxVOTtpSrNw8',
    appId: '1:418778353503:android:b50f04a734415ceaf370ea',
    messagingSenderId: '418778353503',
    projectId: 'fir-flutter-codelab-32edb',
    storageBucket: 'fir-flutter-codelab-32edb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqc4qW47Rn6iUbLWQw98DNMb7ZzDu4etM',
    appId: '1:418778353503:ios:08298d46f5496710f370ea',
    messagingSenderId: '418778353503',
    projectId: 'fir-flutter-codelab-32edb',
    storageBucket: 'fir-flutter-codelab-32edb.appspot.com',
    iosClientId: '418778353503-lep2ef3a0pesinioijtfhc6p79bsbapt.apps.googleusercontent.com',
    iosBundleId: 'com.yhakamay.whoopit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqc4qW47Rn6iUbLWQw98DNMb7ZzDu4etM',
    appId: '1:418778353503:ios:08298d46f5496710f370ea',
    messagingSenderId: '418778353503',
    projectId: 'fir-flutter-codelab-32edb',
    storageBucket: 'fir-flutter-codelab-32edb.appspot.com',
    iosClientId: '418778353503-lep2ef3a0pesinioijtfhc6p79bsbapt.apps.googleusercontent.com',
    iosBundleId: 'com.yhakamay.whoopit',
  );
}
